FROM python:3.8-alpine


WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./


RUN python -m venv .venv &&\
    .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP microblog.py
RUN adduser -D microblog
RUN chown -R microblog:microblog app migrations &&\
    chmod +x boot.sh

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]